
ÉÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»
º                                                                      º
º     ( '>')          Nil OS This is a minimal distribution.           º
º  /) LINUX (\          A Busybox & Fltk minimal desktop.              º
º   (/-_--_-\)              github.com/SlizR/Nil_OS                    º
º                                                                      º
º                                 Version 6.5                          º
ÈÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍŒ

Welcome to Nil OS! This is a minimal distribution for enthusiasts
who build custom builds where simplicity is needed and, most importantly, a UI/GUI

Booting from this CD will first load your regular extensions (if any),
then load the additional extensions for installation, networking, and 
remastering.

Press <Enter> for Nil OS 
Or Press F2, F3, or F4 to view additional boot options, F1 returns here.
